### ISSUE TITLE
Infinity:NaN:NaN without a service worker (dom.serviceWorkers.enabled false)

### ISSUE THREAD

**Issue by grahamperrin** [PaulKinlan/videocut#1]
With `dom.serviceWorkers.enabled` `false`: 

![2018-05-30 13 18 18 waterfox](https://user-images.githubusercontent.com/192271/40719685-350a49d6-640c-11e8-9519-5ae5c1dd5626.png)

Waterfox 56.2.0.19 on FreeBSD-CURRENT. 

I guess, the simple explanation is that for its timeline to work reliably – from the outset (after drop of a video) – Video Trimmer requires its service worker. True? 

TIA

**Comment by PaulKinlan** [comment]
It's not a service worker that's needed. Your end time isn't set up.

**Comment by grahamperrin** [comment]
Oh, this is weird, I get the symptom – 

> Infinity:NaN:NaN

– immediately after dropping the file on the window but not in all profiles. 

My very heavily extended 'everyday' profile is fine. 

A much cleaner 'e10s' profile seems to be bugged. Investigating now …
